// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: room_model.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 加入游戏时对应的游戏 id
// 一场游戏的 id；全局唯一；不能有两场游戏 id 一样。
type DataOfJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DataOfJoin) Reset() {
	*x = DataOfJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataOfJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataOfJoin) ProtoMessage() {}

func (x *DataOfJoin) ProtoReflect() protoreflect.Message {
	mi := &file_room_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataOfJoin.ProtoReflect.Descriptor instead.
func (*DataOfJoin) Descriptor() ([]byte, []int) {
	return file_room_model_proto_rawDescGZIP(), []int{0}
}

func (x *DataOfJoin) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RoomState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount     int32  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Max        int32  `protobuf:"varint,4,opt,name=max,proto3" json:"max,omitempty"` // 房间最大用户数量
	TimeUpdate int32  `protobuf:"varint,5,opt,name=timeUpdate,proto3" json:"timeUpdate,omitempty"`
}

func (x *RoomState) Reset() {
	*x = RoomState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomState) ProtoMessage() {}

func (x *RoomState) ProtoReflect() protoreflect.Message {
	mi := &file_room_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomState.ProtoReflect.Descriptor instead.
func (*RoomState) Descriptor() ([]byte, []int) {
	return file_room_model_proto_rawDescGZIP(), []int{1}
}

func (x *RoomState) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoomState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomState) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RoomState) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *RoomState) GetTimeUpdate() int32 {
	if x != nil {
		return x.TimeUpdate
	}
	return 0
}

type RoomDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount     uint32           `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`         // 房间当前用户数量
	Max        uint32           `protobuf:"varint,4,opt,name=max,proto3" json:"max,omitempty"`               // 房间最大用户数量
	TimeUpdate uint32           `protobuf:"varint,5,opt,name=timeUpdate,proto3" json:"timeUpdate,omitempty"` // 房间信息的最后更新时间
	Roles      []*RoleDetailed  `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`            // 房间内的用户
	Npcs       []*RoleDetailed  `protobuf:"bytes,7,rep,name=npcs,proto3" json:"npcs,omitempty"`              // 房间内非玩家角色
	Messages   []*RoomMsgRecord `protobuf:"bytes,8,rep,name=messages,proto3" json:"messages,omitempty"`      // 房间历史聊天记录
}

func (x *RoomDetail) Reset() {
	*x = RoomDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDetail) ProtoMessage() {}

func (x *RoomDetail) ProtoReflect() protoreflect.Message {
	mi := &file_room_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDetail.ProtoReflect.Descriptor instead.
func (*RoomDetail) Descriptor() ([]byte, []int) {
	return file_room_model_proto_rawDescGZIP(), []int{2}
}

func (x *RoomDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomDetail) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RoomDetail) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *RoomDetail) GetTimeUpdate() uint32 {
	if x != nil {
		return x.TimeUpdate
	}
	return 0
}

func (x *RoomDetail) GetRoles() []*RoleDetailed {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RoomDetail) GetNpcs() []*RoleDetailed {
	if x != nil {
		return x.Npcs
	}
	return nil
}

func (x *RoomDetail) GetMessages() []*RoomMsgRecord {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 房间内聊天记录信息
type RoomMsgRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time    string    `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Role    *RoleInfo `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content string    `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *RoomMsgRecord) Reset() {
	*x = RoomMsgRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomMsgRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMsgRecord) ProtoMessage() {}

func (x *RoomMsgRecord) ProtoReflect() protoreflect.Message {
	mi := &file_room_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMsgRecord.ProtoReflect.Descriptor instead.
func (*RoomMsgRecord) Descriptor() ([]byte, []int) {
	return file_room_model_proto_rawDescGZIP(), []int{3}
}

func (x *RoomMsgRecord) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *RoomMsgRecord) GetRole() *RoleInfo {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *RoomMsgRecord) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RoleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_room_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_room_model_proto_rawDescGZIP(), []int{4}
}

func (x *RoleInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// 角色/英雄信息
type RoleDetailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleInfo   *RoleInfo        `protobuf:"bytes,1,opt,name=roleInfo,proto3" json:"roleInfo,omitempty"`
	State      *RoleState       `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Attributes map[string]int32 `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *RoleDetailed) Reset() {
	*x = RoleDetailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleDetailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDetailed) ProtoMessage() {}

func (x *RoleDetailed) ProtoReflect() protoreflect.Message {
	mi := &file_room_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDetailed.ProtoReflect.Descriptor instead.
func (*RoleDetailed) Descriptor() ([]byte, []int) {
	return file_room_model_proto_rawDescGZIP(), []int{5}
}

func (x *RoleDetailed) GetRoleInfo() *RoleInfo {
	if x != nil {
		return x.RoleInfo
	}
	return nil
}

func (x *RoleDetailed) GetState() *RoleState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *RoleDetailed) GetAttributes() map[string]int32 {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type RoleState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pos *RolePosition `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *RoleState) Reset() {
	*x = RoleState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleState) ProtoMessage() {}

func (x *RoleState) ProtoReflect() protoreflect.Message {
	mi := &file_room_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleState.ProtoReflect.Descriptor instead.
func (*RoleState) Descriptor() ([]byte, []int) {
	return file_room_model_proto_rawDescGZIP(), []int{6}
}

func (x *RoleState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleState) GetPos() *RolePosition {
	if x != nil {
		return x.Pos
	}
	return nil
}

// 玩家位置信息
type RolePosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"` // x 轴坐标
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"` // y 轴坐标
	Z int32 `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"` // z 轴坐标
}

func (x *RolePosition) Reset() {
	*x = RolePosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_model_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePosition) ProtoMessage() {}

func (x *RolePosition) ProtoReflect() protoreflect.Message {
	mi := &file_room_model_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePosition.ProtoReflect.Descriptor instead.
func (*RolePosition) Descriptor() ([]byte, []int) {
	return file_room_model_proto_rawDescGZIP(), []int{7}
}

func (x *RolePosition) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RolePosition) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RolePosition) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_room_model_proto protoreflect.FileDescriptor

var file_room_model_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x74, 0x68, 0x72, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x22, 0x1c, 0x0a, 0x0a,
	0x44, 0x61, 0x74, 0x61, 0x4f, 0x66, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x79, 0x0a, 0x09, 0x52, 0x6f,
	0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x89, 0x02, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d,
	0x61, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x74, 0x68, 0x72, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x12, 0x2a, 0x0a, 0x04, 0x6e, 0x70, 0x63, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x74, 0x68, 0x72, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x52, 0x04, 0x6e, 0x70, 0x63, 0x73, 0x12, 0x33, 0x0a, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x74, 0x68, 0x72, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x22, 0x65, 0x0a, 0x0d, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x68, 0x72, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x36, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0xf0, 0x01, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x68, 0x72, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x74, 0x68, 0x72, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x46, 0x0a, 0x0a,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x74, 0x68, 0x72, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x45, 0x0a, 0x09, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x28, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x74, 0x68, 0x72, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x22, 0x38, 0x0a, 0x0c, 0x52, 0x6f,
	0x6c, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x7a, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x68, 0x61, 0x6e, 0x79, 0x75, 0x6a, 0x69, 0x65, 0x2f, 0x74, 0x68,
	0x72, 0x6f, 0x77, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x68, 0x72, 0x6f, 0x77, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_model_proto_rawDescOnce sync.Once
	file_room_model_proto_rawDescData = file_room_model_proto_rawDesc
)

func file_room_model_proto_rawDescGZIP() []byte {
	file_room_model_proto_rawDescOnce.Do(func() {
		file_room_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_model_proto_rawDescData)
	})
	return file_room_model_proto_rawDescData
}

var file_room_model_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_room_model_proto_goTypes = []interface{}{
	(*DataOfJoin)(nil),    // 0: throw.v1.DataOfJoin
	(*RoomState)(nil),     // 1: throw.v1.RoomState
	(*RoomDetail)(nil),    // 2: throw.v1.RoomDetail
	(*RoomMsgRecord)(nil), // 3: throw.v1.RoomMsgRecord
	(*RoleInfo)(nil),      // 4: throw.v1.RoleInfo
	(*RoleDetailed)(nil),  // 5: throw.v1.RoleDetailed
	(*RoleState)(nil),     // 6: throw.v1.RoleState
	(*RolePosition)(nil),  // 7: throw.v1.RolePosition
	nil,                   // 8: throw.v1.RoleDetailed.AttributesEntry
}
var file_room_model_proto_depIdxs = []int32{
	5, // 0: throw.v1.RoomDetail.roles:type_name -> throw.v1.RoleDetailed
	5, // 1: throw.v1.RoomDetail.npcs:type_name -> throw.v1.RoleDetailed
	3, // 2: throw.v1.RoomDetail.messages:type_name -> throw.v1.RoomMsgRecord
	4, // 3: throw.v1.RoomMsgRecord.role:type_name -> throw.v1.RoleInfo
	4, // 4: throw.v1.RoleDetailed.roleInfo:type_name -> throw.v1.RoleInfo
	6, // 5: throw.v1.RoleDetailed.state:type_name -> throw.v1.RoleState
	8, // 6: throw.v1.RoleDetailed.attributes:type_name -> throw.v1.RoleDetailed.AttributesEntry
	7, // 7: throw.v1.RoleState.pos:type_name -> throw.v1.RolePosition
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_room_model_proto_init() }
func file_room_model_proto_init() {
	if File_room_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_room_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataOfJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomMsgRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleDetailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_model_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_model_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolePosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_model_proto_goTypes,
		DependencyIndexes: file_room_model_proto_depIdxs,
		MessageInfos:      file_room_model_proto_msgTypes,
	}.Build()
	File_room_model_proto = out.File
	file_room_model_proto_rawDesc = nil
	file_room_model_proto_goTypes = nil
	file_room_model_proto_depIdxs = nil
}
