// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: room_model.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 加入游戏时对应的游戏 id
// 一场游戏的 id；全局唯一；不能有两场游戏 id 一样。
type DataOfJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 平台提供的房间 id | @inject_tag: msgpack:"roomId" json:"roomId"
	RoomId string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId" msgpack:"roomId"`
	// 对局 id | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId string `protobuf:"bytes,2,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 当前玩家的 nft id | @inject_tag: msgpack:"nft" json:"nft"
	Nft int32 `protobuf:"varint,3,opt,name=nft,proto3" json:"nft" msgpack:"nft"`
	// 是否与机器人对战 | @inject_tag: msgpack:"needBot" json:"needBot"
	NeedBot bool `protobuf:"varint,4,opt,name=needBot,proto3" json:"needBot" msgpack:"needBot"`
	// 机器人的 uid | @inject_tag: msgpack:"botId" json:"botId"
	BotId int32 `protobuf:"varint,5,opt,name=botId,proto3" json:"botId" msgpack:"botId"`
	// 机器人的 nft | @inject_tag: msgpack:"botNft" json:"botNft"
	BotNft int32 `protobuf:"varint,6,opt,name=botNft,proto3" json:"botNft" msgpack:"botNft"`
	// 门票 | @inject_tag: msgpack:"ticket" json:"ticket"
	Ticket float32 `protobuf:"fixed32,7,opt,name=ticket,proto3" json:"ticket" msgpack:"ticket"`
	// 对战类型，区分 1v1，淘汰赛等 | @inject_tag: msgpack:"pvpType" json:"pvpType"
	PvpType int32 `protobuf:"varint,8,opt,name=pvpType,proto3" json:"pvpType" msgpack:"pvpType"`
	// 机器人的 ai 策略类型 | @inject_tag: msgpack:"aiPolicyType" json:"aiPolicyType"
	AiPolicyType int32 `protobuf:"varint,9,opt,name=aiPolicyType,proto3" json:"aiPolicyType" msgpack:"aiPolicyType"`
}

func (x *DataOfJoin) Reset() {
	*x = DataOfJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataOfJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataOfJoin) ProtoMessage() {}

func (x *DataOfJoin) ProtoReflect() protoreflect.Message {
	mi := &file_room_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataOfJoin.ProtoReflect.Descriptor instead.
func (*DataOfJoin) Descriptor() ([]byte, []int) {
	return file_room_model_proto_rawDescGZIP(), []int{0}
}

func (x *DataOfJoin) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DataOfJoin) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *DataOfJoin) GetNft() int32 {
	if x != nil {
		return x.Nft
	}
	return 0
}

func (x *DataOfJoin) GetNeedBot() bool {
	if x != nil {
		return x.NeedBot
	}
	return false
}

func (x *DataOfJoin) GetBotId() int32 {
	if x != nil {
		return x.BotId
	}
	return 0
}

func (x *DataOfJoin) GetBotNft() int32 {
	if x != nil {
		return x.BotNft
	}
	return 0
}

func (x *DataOfJoin) GetTicket() float32 {
	if x != nil {
		return x.Ticket
	}
	return 0
}

func (x *DataOfJoin) GetPvpType() int32 {
	if x != nil {
		return x.PvpType
	}
	return 0
}

func (x *DataOfJoin) GetAiPolicyType() int32 {
	if x != nil {
		return x.AiPolicyType
	}
	return 0
}

type PveJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 关卡 id | @inject_tag: msgpack:"levelId"
	LevelId int32 `protobuf:"varint,1,opt,name=levelId,proto3" json:"levelId,omitempty" msgpack:"levelId"`
	// nft id | @inject_tag: msgpack:"nft"
	Nft int32 `protobuf:"varint,2,opt,name=nft,proto3" json:"nft,omitempty" msgpack:"nft"`
}

func (x *PveJoin) Reset() {
	*x = PveJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PveJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PveJoin) ProtoMessage() {}

func (x *PveJoin) ProtoReflect() protoreflect.Message {
	mi := &file_room_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PveJoin.ProtoReflect.Descriptor instead.
func (*PveJoin) Descriptor() ([]byte, []int) {
	return file_room_model_proto_rawDescGZIP(), []int{1}
}

func (x *PveJoin) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *PveJoin) GetNft() int32 {
	if x != nil {
		return x.Nft
	}
	return 0
}

var File_room_model_proto protoreflect.FileDescriptor

var file_room_model_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x74, 0x68, 0x72, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x22, 0xec, 0x01, 0x0a,
	0x0a, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x66, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e,
	0x66, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x66, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6e, 0x65, 0x65, 0x64, 0x42, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x6e, 0x65, 0x65, 0x64, 0x42, 0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x6f, 0x74, 0x4e, 0x66, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62,
	0x6f, 0x74, 0x4e, 0x66, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x76, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x70, 0x76, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x69, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x61,
	0x69, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0x35, 0x0a, 0x07, 0x50,
	0x76, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e,
	0x66, 0x74, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x75, 0x68, 0x61, 0x6e, 0x79, 0x75, 0x6a, 0x69, 0x65, 0x2f, 0x74, 0x68, 0x72, 0x6f,
	0x77, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x74, 0x68, 0x72, 0x6f, 0x77, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_model_proto_rawDescOnce sync.Once
	file_room_model_proto_rawDescData = file_room_model_proto_rawDesc
)

func file_room_model_proto_rawDescGZIP() []byte {
	file_room_model_proto_rawDescOnce.Do(func() {
		file_room_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_model_proto_rawDescData)
	})
	return file_room_model_proto_rawDescData
}

var file_room_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_room_model_proto_goTypes = []interface{}{
	(*DataOfJoin)(nil), // 0: throw.v1.DataOfJoin
	(*PveJoin)(nil),    // 1: throw.v1.PveJoin
}
var file_room_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_room_model_proto_init() }
func file_room_model_proto_init() {
	if File_room_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_room_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataOfJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PveJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_model_proto_goTypes,
		DependencyIndexes: file_room_model_proto_depIdxs,
		MessageInfos:      file_room_model_proto_msgTypes,
	}.Build()
	File_room_model_proto = out.File
	file_room_model_proto_rawDesc = nil
	file_room_model_proto_goTypes = nil
	file_room_model_proto_depIdxs = nil
}
